apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-device-info #host name
  labels:
    app: m-device-info
spec:
  replicas: 4
  selector:
    matchLabels:
      app: m-device-info
  template:
    metadata:
      labels:
        app: m-device-info
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - "2" # Select nodes with label 'node=2' for the first replica
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - "3"
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - "4"
              - matchExpressions:
                    - key: node
                      operator: In
                      values:
                        - "5"
      containers:
          - name: m-service-container
            image: busybox:latest
            command: ["/bin/sh", "-c", "nc -k -lp 8080 -e echo 'HI'"]
            # command: ["/bin/sh", "-c", "echo '---'; echo 'Ping to node: $node'; ping -c 5 $node; done"]
            ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-device-info
spec:
  selector:
    app: m-device-info
  ports:
    - protocol: TCP
      name: m-device-info-port
      port: 8080
      targetPort: 8080